###############################################################################
# Example user configuration file for ESMValTool
###############################################################################
#
# Note for users:
# --------------
# Site-specific entries for different HPC centers are given at the bottom of
# this file. Comment out/replace as needed. This default version of the file
# can be used in combination with the command line argument ``offline=False``
# If only certain values are allowed for an option, these are listed after
# ``---``. The option in square brackets is the default value, i.e., the one
# that is used if this option is omitted in the file.
#
###############################################################################
#
# Note for developers:
# -------------------
# Two identical copies of this file (``ESMValTool/config-user-example.yml`` and
# ``ESMValCore/esmvalcore/config-user.yml``) exist. If you change one of it,
# make sure to apply the changes to the other.
#
###############################################################################
---

# Destination directory where all output will be written
# Includes log files and performance stats.
output_dir: /g/data/kj13/NRI/esmvaltool_output

# Directory for storing downloaded climate data
download_dir: /g/data/kj13/datasets/esmvaltool/esmvaltool_climate_data

# Auxiliary data directory
# Used by some recipes to look for additional datasets.
auxiliary_data_dir: /g/data/kj13/datasets/auxiliary_data

# Automatic data download from ESGF --- [never]/when_missing/always
# Use automatic download of missing CMIP3, CMIP5, CMIP6, CORDEX, and obs4MIPs
# data from ESGF. ``never`` disables this feature, which is useful if you are
# working on a computer without an internet connection, or if you have limited
# disk space. ``when_missing`` enables the automatic download for files that
# are not available locally. ``always`` will always check ESGF for the latest
# version of a file, and will only use local files if they correspond to that
# latest version.
search_esgf: when_missing

# Run at most this many tasks in parallel --- [null]/1/2/3/4/...
# Set to ``null`` to use the number of available CPUs. If you run out of
# memory, try setting max_parallel_tasks to ``1`` and check the amount of
# memory you need for that by inspecting the file ``run/resource_usage.txt`` in
# the output directory. Using the number there you can increase the number of
# parallel tasks again to a reasonable number for the amount of memory
# available in your system.
max_parallel_tasks: null

# Log level of the console --- debug/[info]/warning/error
# For much more information printed to screen set log_level to ``debug``.
log_level: debug

# Exit on warning --- true/[false]
# # Only used in NCL diagnostic scripts.
exit_on_warning: false

# Plot file format --- [png]/pdf/ps/eps/epsi
output_file_type: png

# Remove the ``preproc`` directory if the run was successful --- [true]/false
# By default this option is set to ``true``, so all preprocessor output files
# will be removed after a successful run. Set to ``false`` if you need those
# files.
remove_preproc_dir: true

# Use netCDF compression --- true/[false]
compress_netcdf: false

# Save intermediary cubes in the preprocessor --- true/[false]
# Setting this to ``true`` will save the output cube from each preprocessing
# step. These files are numbered according to the preprocessing order.
save_intermediary_cubes: false

# Path to custom ``config-developer.yml`` file
# This can be used to customise project configurations. See
# ``config-developer.yml`` for an example. Set to ``null`` to use the default.
config_developer_file: /g/data/kj13/admin/ESMValTool/.esmvaltool/config-developer.yml

# Use a profiling tool for the diagnostic run --- [false]/true
# A profiler tells you which functions in your code take most time to run.
# Only available for Python diagnostics.
profile_diagnostic: false

extra_facets_dir: /g/data/kj13/admin/ESMValTool/.esmvaltool/extra_facets

# Rootpaths to the data from different projects
# This default setting will work if files have been downloaded by the
# ESMValTool via ``offline=False``. Lists are also possible. For site-specific
# entries and more examples, see below. Comment out these when using a
# site-specific path.
rootpath:
  default: /g/data/kj13/datasets/esmvaltool/esmvaltool_climate_data/CMIP6
  CMIP6: [/g/data/oi10/replicas/CMIP6, /g/data/fs38/publications/CMIP6, /g/data/kj13/datasets/esmvaltool/esmvaltool_climate_data/CMIP6]
  CMIP5: [/g/data/r87/DRSv3/CMIP5, /g/data/al33/replicas/CMIP5/combined, /g/data/rr3/publications/CMIP5/output1, /g/data/kj13/datasets/esmvaltool/esmvaltool_climate_data/cmip5/output1]
  CMIP3: [/g/data/cb20/replicas/cmip3, /g/data/kj13/datasets/esmvaltool/esmvaltool_climate_data/cmip3]
  OBS: /g/data/kj13/datasets/esmvaltool/obsdata-v2
  OBS6: /g/data/kj13/datasets/esmvaltool/obsdata-v2
  native6: /g/data/kj13/datasets/esmvaltool/raw-data
  RAWOBS: /g/data/kj13/datasets/esmvaltool/raw-data
  obs4MIPs: /g/data/kj13/datasets/esmvaltool/obsdata-v2
  obs4mips: /g/data/kj13/datasets/esmvaltool/obsdata-v2
  #obs4MIPs: /g/data/qv56/replicas/obs4MIPs
  #obs4mips: /g/data/qv56/replicas/obs4MIPs

# Directory structure for input data --- [default]/ESGF/BADC/DKRZ/ETHZ/etc.
# This default setting will work if files have been downloaded by the
# ESMValTool via ``offline=False``. See ``config-developer.yml`` for
# definitions. Comment out/replace as per needed.
drs:
  CMIP3: NCI
  CMIP5: BADC
  CMIP6: BADC
  CORDEX: ESGF
  obs4MIPs: default
  ana4mips: default

