name: Recipe Name
 
on:
  workflow_run:
    workflows: [ "Workflow Main" ]
    types:
      - completed
  workflow_dispatch:
 
jobs:
  work:
    name: Running Recipe
    runs-on: ubuntu-latest
    steps:
      - run: echo "Some work"

