name: Update Auxiliary data
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run rsync job
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: gadi.nci.org.au
          username: ${{secrets.GADI_USER}}
          key: ${{secrets.DEPLOY_KEY}}
          command_timeout: 600m
          script: |
            cd ${{secrets.GADI_SCRIPTS_DIR}}
            qsub esmval_auxdata_update.pbs
